version: '3.8'

networks:
  dev:
    driver: bridge

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5500:80"
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;User Id=myuser;Password=mypassword
    networks:
      - dev
    command: >
      bash -c "dotnet ef database update && dotnet watch run"

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
