version: '3.8'

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile 
    ports:
      - "5500:80"  # Puedes ajustar el puerto según tu configuración
    depends_on:
      - react

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Puedes ajustar el puerto según tu configuración
  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Puedes ajustar el puerto según tu configuración
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
