-- init.sql
CREATE USER myuser WITH PASSWORD 'mypassword';
ALTER USER myuser WITH CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE mydatabase TO myuser;

GRANT USAGE, CREATE ON SCHEMA public TO myuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO myuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO myuser;
